[DEFAULT]
log_root=/var/log/manga
celery_log_file=%(log_root)s/celery.log

[loggers]
keys=root,backend_fastapi,celery,gunicorn.error,gunicorn.access,postgres,nginx.access,nginx.error

[handlers]
keys=consoleHandler,fastapiFileHandler,celeryFileHandler,gunicornErrorFileHandler,gunicornAccessFileHandler,postgresFileHandler,nginxAccessFileHandler,nginxErrorFileHandler

[formatters]
keys=defaultFormatter,accessFormatter,syslogFormatter

[logger_root]
level=INFO
handlers=consoleHandler

[logger_backend_fastapi]
level=DEBUG
handlers=consoleHandler,fastapiFileHandler
qualname=backend_fastapi
propagate=0

[logger_celery]
level=INFO
handlers=consoleHandler,celeryFileHandler
qualname=celery
propagate=0

[logger_gunicorn.error]
level=INFO
handlers=consoleHandler,gunicornErrorFileHandler
qualname=gunicorn.error
propagate=0

[logger_gunicorn.access]
level=INFO
handlers=gunicornAccessFileHandler
qualname=gunicorn.access
propagate=0

[logger_postgres]
level=INFO
handlers=postgresFileHandler
qualname=postgres
propagate=0

[logger_nginx.access]
level=INFO
handlers=nginxAccessFileHandler
qualname=nginx.access
propagate=0

[logger_nginx.error]
level=INFO
handlers=nginxErrorFileHandler
qualname=nginx.error
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=defaultFormatter
args=(sys.stdout,)

[handler_fastapiFileHandler]
class=logging.handlers.TimedRotatingFileHandler
level=INFO
formatter=defaultFormatter
args=('%(log_root)s/backend-fastapi-app.log', 'midnight', 1, 14)

[handler_celeryFileHandler]
class=logging.handlers.TimedRotatingFileHandler
level=INFO
formatter=defaultFormatter
args=('%(celery_log_file)s', 'midnight', 1, 14)

[handler_gunicornErrorFileHandler]
class=logging.handlers.TimedRotatingFileHandler
level=INFO
formatter=defaultFormatter
args=('%(log_root)s/gunicorn-error.log', 'midnight', 1, 30)

[handler_gunicornAccessFileHandler]
class=logging.handlers.TimedRotatingFileHandler
level=INFO
formatter=accessFormatter
args=('%(log_root)s/gunicorn-access.log', 'midnight', 1, 30)

[handler_postgresFileHandler]
class=logging.handlers.WatchedFileHandler
level=INFO
formatter=defaultFormatter
args=('%(log_root)s/postgres.log', 'a')

[handler_nginxAccessFileHandler]
class=logging.handlers.WatchedFileHandler
level=INFO
formatter=syslogFormatter
args=('%(log_root)s/nginx-access.log', 'a')

[handler_nginxErrorFileHandler]
class=logging.handlers.WatchedFileHandler
level=INFO
formatter=syslogFormatter
args=('%(log_root)s/nginx-error.log', 'a')

[formatter_defaultFormatter]
format=%(asctime)s [%(levelname)s] %(name)s: %(message)s
datefmt=%Y-%m-%d %H:%M:%S

[formatter_accessFormatter]
format=%(asctime)s %(message)s
datefmt=%Y-%m-%d %H:%M:%S

[formatter_syslogFormatter]
format=%(asctime)s %(name)s: %(message)s
datefmt=%Y-%m-%d %H:%M:%S
